### ISSUE TITLE
ClassNotFoundException: org.netbeans.modules.form.layoutdesign.LayoutPainter

### ISSUE THREAD

**Issue by vt99** [Revivius/nb-darcula#130]
I have **ClassNotFoundException** when using darcula:
[nb-darcula-exc.txt](https://github.com/Revivius/nb-darcula/files/587675/nb-darcula-exc.txt)

Stacktrace:
```
java.lang.ClassNotFoundException: org.netbeans.modules.form.layoutdesign.LayoutPainter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
```

**Comment by AlexFalappa** [comment]
This is not a problem: it usually happens in applications built on the NetBeans Platform that do not include all the modules of the NetBeans IDE, the Darcula LAF does not manage to find certain classes to tweak colors by using reflection. You can notice that the message is not at ERROR level but INFO.

I made a pull request ( #97 ) to hide the stack traces to reduce the perceived severity of the problem but it has not been merged yet.

**Comment by vt99** [comment]
Thank you for your explanation.
