### ISSUE TITLE
IlligalArgumentException on hitting f1 for getting help

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#134]
I wanted to search smth inside the help, I don't do it often, but sometimes I do. So I hit F1 and I got this exception:

```
java.lang.IllegalArgumentException: view is invalid
	at javax.help.search.MergingSearchEngine.merge(MergingSearchEngine.java:91)
	at javax.help.JHelpSearchNavigator.merge(JHelpSearchNavigator.java:168)
	at javax.help.plaf.basic.BasicSearchNavigatorUI.addSubHelpSets(BasicSearchNavigatorUI.java:275)
	at javax.help.plaf.basic.BasicSearchNavigatorUI.reloadData(BasicSearchNavigatorUI.java:225)
	at javax.help.plaf.basic.BasicSearchNavigatorUI.installUI(BasicSearchNavigatorUI.java:174)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.help.JHelpNavigator.setUI(JHelpNavigator.java:257)
	at javax.help.JHelpNavigator.updateUI(JHelpNavigator.java:276)
	at javax.help.JHelpNavigator.<init>(JHelpNavigator.java:105)
	at javax.help.JHelpSearchNavigator.<init>(JHelpSearchNavigator.java:66)
	at javax.help.SearchView.createNavigator(SearchView.java:80)
	at javax.help.JHelp.setupNavigators(JHelp.java:148)
	at javax.help.JHelp.<init>(JHelp.java:126)
	at javax.help.JHelp.<init>(JHelp.java:76)
[catch] at org.netbeans.modules.javahelp.JavaHelp.createJHelp(JavaHelp.java:1021)
	at org.netbeans.modules.javahelp.JavaHelp.createAndDisplayJHelp(JavaHelp.java:554)
	at org.netbeans.modules.javahelp.JavaHelp.showHelp(JavaHelp.java:533)
	at org.netbeans.api.javahelp.Help.showHelp(Help.java:77)
	at org.netbeans.modules.javahelp.HelpAction.actionPerformed(HelpAction.java:184)
	at org.openide.windows.TopComponent.processKeyBinding(TopComponent.java:1176)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2943)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by markiewb** [comment]
I doubt that it is a bug in darcula. I see no traces of that in the stack
trace.

Den 18 jan. 2017 10:50 skrev "Chrizzly" <notifications@github.com>:

**Comment by Chris2011** [comment]
Ok let me check it again. I thought it has smth todo with darcula because of the part with the "plaf".

**Comment by Chris2011** [comment]
Thx, it seems that this is a problem with this plugin: http://plugins.netbeans.org/plugin/70044/title-bar.
