### ISSUE TITLE
NetBeans 9.0 compatibility

### ISSUE THREAD

**Issue by stefanwendelmann** [Revivius/nb-darcula#158]
`INFO [com.revivius.nb.darcula.DarculaLFCustoms]: Can not find class, will not be able to replace its field...
java.lang.ClassNotFoundException: org.netbeans.modules.web.core.syntax.completion.api.JspCompletionItem
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:197)
Caused: java.lang.ClassNotFoundException: org.netbeans.modules.web.core.syntax.completion.api.JspCompletionItem starting from SystemClassLoader[549 modules] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@11a9aee9, ModuleCL@224c3efe[org.netbeans.api.annotations.common], ModuleCL@192eb668[org.openide.awt], ModuleCL@eb9e219[org.netbeans.api.progress], ModuleCL@e461658[org.netbeans.api.intent], ModuleCL@4d3e62a0[org.netbeans.api.io], ModuleCL@21cf1099[org.openide.io], ModuleCL@60a78793[org.netbeans.api.progress.nb], ModuleCL@5e6da909[org.netbeans.modules.extexecution.base], ModuleCL@6078eb06[org.netbeans.modules.extexecution], ...527 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:199)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:754)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
[catch] at com.revivius.nb.darcula.DarculaLFCustoms.replaceFieldValue(DarculaLFCustoms.java:751)
	at com.revivius.nb.darcula.DarculaLFCustoms.replaceJSPCompletionColor(DarculaLFCustoms.java:683)
	at com.revivius.nb.darcula.DarculaLFCustoms.createLookAndFeelCustomizationKeysAndValues(DarculaLFCustoms.java:291)
	at org.netbeans.swing.plaf.LFCustoms.getLookAndFeelCustomizationKeysAndValues(LFCustoms.java:171)
	at org.netbeans.swing.plaf.Startup.installLFCustoms(Startup.java:325)
	at org.netbeans.swing.plaf.Startup.installPerLFDefaults(Startup.java:250)
	at org.netbeans.swing.plaf.Startup.install(Startup.java:228)
	at org.netbeans.swing.plaf.Startup.run(Startup.java:527)
	at org.netbeans.core.CoreBridgeImpl$1$1.run(CoreBridgeImpl.java:112)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by AlexFalappa** [comment]
This is not a real bug, it only means that NBDarcula could not tweak the LAF of some NB plugins (JSP completion in this case) via reflection because they are not installed.

Even if the big, scaring  stacktrace is reported that is only an INFO message.

I tried to mitigate this with PR #97 long time ago but it was not merged.
