### ISSUE TITLE
Problem with Netbeans Signer plugin

### ISSUE THREAD

**Issue by Chris2011** [Revivius/nb-darcula#36]
Before I used Darcula I head no problems with the Netbeans signer plugin: http://plugins.netbeans.org/plugin/9499/netbeans-signer

No I got an exception, when I click on the button "Create keystore..."

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.bulenkov.darcula.ui.DarculaSpinnerUI.replaceEditor(DarculaSpinnerUI.java:60)
	at javax.swing.plaf.basic.BasicSpinnerUI$Handler.propertyChange(BasicSpinnerUI.java:974)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at javax.swing.JSpinner.setEditor(JSpinner.java:520)
	at com.toedter.components.JSpinField.<init>(Unknown Source)
	at com.toedter.components.JSpinField.<init>(Unknown Source)
	at com.toedter.calendar.JYearChooser.<init>(Unknown Source)
	at com.toedter.calendar.JCalendar.<init>(Unknown Source)
	at com.toedter.calendar.JCalendar.<init>(Unknown Source)
	at com.toedter.calendar.JDateChooser.<init>(Unknown Source)
	at com.toedter.calendar.JDateChooser.<init>(Unknown Source)
	at org.netbeans.modules.signer.gui.KeystoreCreatorDialog.initComponents(KeystoreCreatorDialog.java:65)
	at org.netbeans.modules.signer.gui.KeystoreCreatorDialog.<init>(KeystoreCreatorDialog.java:33)
	at org.netbeans.modules.signer.gui.WindowManager.showKeystoreCreator(WindowManager.java:35)
	at org.netbeans.modules.signer.gui.NBSignerDialog.jBtnCreateKeystoreActionPerformed(NBSignerDialog.java:257)
	at org.netbeans.modules.signer.gui.NBSignerDialog.access$200(NBSignerDialog.java:24)
	at org.netbeans.modules.signer.gui.NBSignerDialog$3.actionPerformed(NBSignerDialog.java:143)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Regards

Chris

**Comment by markiewb** [comment]
Issue in here?
https://github.com/bulenkov/Darcula/blob/c91f937e8feef3a8ba1f56ede628f3da3e7de33b/src/com/bulenkov/darcula/ui/DarculaSpinnerUI.java#L54

**Comment by Revivius** [comment]
@markiewb I think you are right. I had to copy paste the original DarculaSpinnerUI to add a length check. See:

https://github.com/Revivius/nb-darcula/blob/master/src/main/java/com/revivius/nb/darcula/ui/SafeDarculaSpinnerUI.java

@Chris2011 can you please verify ?

**Comment by Chris2011** [comment]
It works. Thx :)

**Comment by Revivius** [comment]
Nice!

**Comment by AlexFalappa** [comment]
I stumbled on this issue when opening in the visual designer a form with toedter.com JCalendar Swing widget at work: got the same exception and the visual designer suggested not to make the form editable.

I applied the fix to a custom darcula.jar and have made a Pull Request with this fix to the original project.
See https://github.com/bulenkov/Darcula/pull/14
