### ISSUE TITLE
java.lang.ClassNotFoundException: org.netbeans.modules.form.layoutdesign.LayoutPainter

### ISSUE THREAD

**Issue by bazo** [Revivius/nb-darcula#56]
hi, netbeans dev version

when starting ide this exception is thrown

java.lang.ClassNotFoundException: org.netbeans.modules.form.layoutdesign.LayoutPainter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: org.netbeans.modules.form.layoutdesign.LayoutPainter starting from SystemClassLoader[415 modules] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@2e5d6d97, ModuleCL@35f11c9d[org.netbeans.api.annotations.common], ModuleCL@24113f75[org.openide.awt], ModuleCL@1ec4b158[org.netbeans.api.progress], ModuleCL@1f55a065[org.netbeans.api.progress.nb], ModuleCL@731a421f[org.openide.dialogs], ModuleCL@65963759[org.openide.nodes], ModuleCL@77406304[org.openide.windows], ModuleCL@631073ce[org.netbeans.modules.editor.mimelookup], ModuleCL@1f14f059[org.openide.text], ...395 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:772)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[catch] at com.revivius.nb.darcula.DarculaLFCustoms.replaceFieldValue(DarculaLFCustoms.java:542)
	at com.revivius.nb.darcula.DarculaLFCustoms.replaceFormDesignerGapBorderColors(DarculaLFCustoms.java:511)
	at com.revivius.nb.darcula.DarculaLFCustoms.createLookAndFeelCustomizationKeysAndValues(DarculaLFCustoms.java:231)
	at org.netbeans.swing.plaf.LFCustoms.getLookAndFeelCustomizationKeysAndValues(LFCustoms.java:196)
	at org.netbeans.swing.plaf.Startup.installLFCustoms(Startup.java:350)
	at org.netbeans.swing.plaf.Startup.installPerLFDefaults(Startup.java:275)
	at org.netbeans.swing.plaf.Startup.install(Startup.java:253)
	at org.netbeans.swing.plaf.Startup.run(Startup.java:552)
	at org.netbeans.core.CoreBridgeImpl$1$1.run(CoreBridgeImpl.java:137)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Revivius** [comment]
@bazo; thank you for reporting. 

This was due to logging level used when trying to replace hardcoded fields (mostly colors to match dark LAF) in some classes with reflection. In some cases those classes may not be available   (for example a NetBeans Platform application probably will not contain Visual Form Designer module and hence LayoutPainter class as in this exception) and this is quite normal. So log level should be INFO instead of WARNING and should not cause a dialog to be displayed.

This is already fixed in 9c4a62a56f81302614775689804abccd13ca6219 and will be available in v1.4.
