### ISSUE TITLE
ClassNotFoundException at IDE start

### ISSUE THREAD

**Issue by jmborer** [Revivius/nb-darcula#96]
When I start an empty NB IDE I get this exception in the IDE logs:

INFO [com.revivius.nb.darcula.DarculaLFCustoms]: Can not find class, will not be able to replace its field...
java.lang.ClassNotFoundException: org.netbeans.modules.web.core.syntax.completion.api.JspCompletionItem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:222)
Caused: java.lang.ClassNotFoundException: org.netbeans.modules.web.core.syntax.completion.api.JspCompletionItem starting from SystemClassLoader[537 modules] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@377dca04, ModuleCL@e4e70b0[org.netbeans.api.annotations.common], ModuleCL@58936544[org.netbeans.api.java.classpath], ModuleCL@21f6b60b[org.netbeans.api.java], ModuleCL@38659c93[org.openide.awt], ModuleCL@45d3b0df[org.netbeans.api.progress], ModuleCL@6a95464[org.netbeans.api.progress.nb], ModuleCL@127bfc54[org.openide.dialogs], ModuleCL@66e6b8c[org.openide.nodes], ModuleCL@5e6376d6[org.openide.windows], ...515 more]
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:224)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:766)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[catch] at com.revivius.nb.darcula.DarculaLFCustoms.replaceFieldValue(DarculaLFCustoms.java:710)
	at com.revivius.nb.darcula.DarculaLFCustoms.replaceJSPCompletionColor(DarculaLFCustoms.java:656)
	at com.revivius.nb.darcula.DarculaLFCustoms.createLookAndFeelCustomizationKeysAndValues(DarculaLFCustoms.java:281)
	at org.netbeans.swing.plaf.LFCustoms.getLookAndFeelCustomizationKeysAndValues(LFCustoms.java:196)
	at org.netbeans.swing.plaf.Startup.installLFCustoms(Startup.java:340)
	at org.netbeans.swing.plaf.Startup.installPerLFDefaults(Startup.java:265)
	at org.netbeans.swing.plaf.Startup.install(Startup.java:243)
	at org.netbeans.swing.plaf.Startup.run(Startup.java:542)
	at org.netbeans.core.CoreBridgeImpl$1$1.run(CoreBridgeImpl.java:137)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AlexFalappa** [comment]
That is normal, even if the exception and the stack trace make it look scary, it's an INFO message. 

Basically it means that the web development NetBeans plugins are not present and there are no JSP completion colors to tweak. 

If I have time I can contribute a PR for making these warnings less prominent.

**Comment by Revivius** [comment]
@jmborer; I hope explanation from @AlexFalappa was helpful enough, closing this issue.
